# config/cucumber.yml
##YAML Template
---
android: PLATFORM=android -r features/support -r features/android/support -r features/android/pages -r features/step_definitions

ios: PLATFORM=ios -r features/support -r features/ios/support -r features/ios/pages -r features/step_definitions 
