# config/cucumber.yml
##YAML Template
---
android: PLATFORM=android -r core -r calabash/android/features/support -r step_definitions -r android/features

ios: PLATFORM=ios -r core -r calabash/ios/features/support -r step_definitions -r ios/features
