# config/cucumber.yml
##YAML Template
---
android: PLATFORM=android -r core -r calabash/android/features/support -r features/step_definitions -r features/android/features

ios: PLATFORM=ios -r core -r calabash/ios/features/support -r features/step_definitions -r features/ios/features
