# config/cucumber.yml
##YAML Template
---
android: PLATFORM=android -r features/support -r features/android/support -r features/step_definitions -r features/android/features

ios: PLATFORM=ios -r features/support -r features/ios/support -r features/step_definitions -r features/ios/features
